import { DynamicFieldModel, FormTypes } from "./types";

export const MockDynamicData: DynamicFieldModel[] = [
	{
		mappingId: "1",
		fieldKey: "firstname",
		serviceId: "6",
		fieldTypeId: FormTypes.text,
		fieldId: 1,
		fieldLabel: "First Name",
		serviceFieldOption: [],
		isRequired: true,
		defaultValue: "",
		placeholder: "First Name",
		attributes: { maxLength: "50", minLength: "2" },
	},
	{
		mappingId: "2",
		fieldKey: "mydescription",
		serviceId: "6",
		fieldId: 2,
		fieldTypeId: FormTypes.texteditor,
		fieldLabel: "My Description",
		serviceFieldOption: [],
		isRequired: true,
		defaultValue: "",
		placeholder: "My Description",
		attributes: { maxLength: "50" },
	},
	{
		mappingId: "3",
		fieldKey: "singlecheckbox",
		serviceId: "6",
		fieldId: 3,
		fieldTypeId: FormTypes.checkbox,
		fieldLabel: "Approve Terms and Conditions",
		serviceFieldOption: [],
		isRequired: true,
		defaultValue: "",
		attributes: {},
	},
	{
		mappingId: "4",
		fieldKey: "email",
		serviceId: "6",
		fieldId: 4,
		fieldTypeId: FormTypes.email,
		fieldLabel: "Email",
		serviceFieldOption: [],
		isRequired: true,
		defaultValue: "",
		placeholder: "Email",
		attributes: { maxLength: "50", minLength: "7" },
	},
	{
		mappingId: "5",
		fieldKey: "radiogroup",
		serviceId: "6",
		fieldId: 5,
		fieldTypeId: FormTypes.radiogroup,
		fieldLabel: "Gender",
		serviceFieldOption: [
			{
				label: "Male",
				value: "1",
				fieldId: 1,
				isDefault: false
			},
			{
				label: "Female",
				value: "2",
				fieldId: 1,
				isDefault: false
			},
			{
				label: "Other",
				value: "3",
				fieldId: 1,
				isDefault: false
			}
		],
		isRequired: true,
		defaultValue: "",
		attributes: {},
	},
	{
		mappingId: "7",
		fieldKey: "fruitslist",
		serviceId: "6",
		fieldId: 7,
		fieldTypeId: FormTypes.dropdownlist,
		fieldLabel: "List of Fruits",
		serviceFieldOption: [
			{
				label: "Apple",
				value: 1,
				fieldId: 1,
				isDefault: false
			},
			{
				label: "Banana",
				value: 2,
				fieldId: 1,
				isDefault: false
			},
			{
				label: "Orange",
				value: 3,
				fieldId: 1,
				isDefault: false
			},
			{
				label: "Papaya",
				value: 4,
				fieldId: 1,
				isDefault: false
			}
		],
		isRequired: true,
		defaultValue: "",
		placeholder: "Fruit Selection",
		attributes: {},
	},
	{
		mappingId: "8",
		fieldKey: "textarea",
		serviceId: "6",
		fieldId: 8,
		fieldTypeId: FormTypes.textarea,
		fieldLabel: "My Address",
		serviceFieldOption: [],
		isRequired: true,
		defaultValue: "",
		placeholder: "My Address",
		attributes: { maxLength: "50", minLength: "2" },
	},
	{
		mappingId: "9",
		fieldKey: "number",
		serviceId: "6",
		fieldId: 9,
		fieldTypeId: FormTypes.number,
		fieldLabel: "My contact number",
		serviceFieldOption: [],
		isRequired: true,
		defaultValue: "200",
		placeholder: "My contact number",
		attributes: { maxLength: "4", minLength: "3", minValue: "10", maxValue: "500" },
	},
	{
		mappingId: "10",
		fieldKey: "mydate",
		serviceId: "6",
		fieldId: 10,
		fieldTypeId: FormTypes.date,
		fieldLabel: "My date of birth",
		serviceFieldOption: [],
		isRequired: true,
		defaultValue: "",
		attributes: { minValue: "2025/05/01", maxValue: "2025/06/30" },
	},
	{
		mappingId: "11",
		fieldKey: "mytime",
		serviceId: "6",
		fieldId: 11,
		fieldTypeId: FormTypes.time,
		fieldLabel: "My time of birth",
		serviceFieldOption: [],
		isRequired: true,
		defaultValue: "",
		attributes: { minValue: "08:00", maxValue: "20:00" },
	},
	{
		mappingId: "12",
		fieldKey: "myurl",
		serviceId: "6",
		fieldId: 12,
		fieldTypeId: FormTypes.url,
		fieldLabel: "URL",
		serviceFieldOption: [],
		isRequired: true,
		defaultValue: "",
		placeholder: "Enter URL",
		attributes: { minValue: "10", maxValue: "50" },
	},
	{
		mappingId: "13",
		fieldKey: "mydecimal",
		serviceId: "6",
		fieldId: 13,
		fieldTypeId: FormTypes.decimal,
		fieldLabel: "Decimal Number",
		serviceFieldOption: [],
		isRequired: true,
		defaultValue: "",
		placeholder: "Enter a decimal number",
		attributes: { minValue: "1.005", maxValue: "50.003", maxLength: "10", minLength: "2", decimalPlaces: "3" },
	},
	{
		mappingId: "14",
		fieldKey: "autocomplete",
		serviceId: "6",
		fieldId: 14,
		fieldTypeId: FormTypes.autocompletedropdownlist,
		fieldLabel: "Auto Fruit Choices",
		serviceFieldOption: [
			{
				label: "Apple",
				value: 1,
				fieldId: 1,
				isDefault: false
			},
			{
				label: "Banana",
				value: 2,
				fieldId: 1,
				isDefault: false
			},
			{
				label: "Orange",
				value: 3,
				fieldId: 1,
				isDefault: false
			},
			{
				label: "Papaya",
				value: 4,
				fieldId: 1,
				isDefault: false
			}
		],
		isRequired: true,
		defaultValue: "",
		placeholder: "Search fruits...",
		attributes: {},
	},
]