import { DynamicFieldModel, FormTypes } from "./types";

export const MockStaticData: DynamicFieldModel[] = [
    {
        mappingId: "requestorCamp",
        fieldKey: "requestorCamp",
        serviceId: "static",
        fieldTypeId: FormTypes.text,
        fieldId: 1001,
        fieldLabel: "Requestor Camp",
        serviceFieldOption: [],
        isRequired: true,
        defaultValue: "",
        placeholder: "Requestor Camp",
        attributes: {}
    },
    {
        mappingId: "requestorMobileNumber",
        fieldKey: "requestorMobileNumber",
        serviceId: "static",
        fieldTypeId: FormTypes.text,
        fieldId: 1002,
        fieldLabel: "Requestor Mobile Number",
        serviceFieldOption: [],
        isRequired: true,
        defaultValue: "",
        placeholder: "Requestor Mobile Number",
        attributes: {},
    },
    {
        mappingId: "requestorExtension",
        fieldKey: "requestorExtension",
        serviceId: "static",
        fieldTypeId: FormTypes.text,
        fieldId: 1003,
        fieldLabel: "Requestor Extension",
        serviceFieldOption: [],
        isRequired: false,
        defaultValue: "",
        placeholder: "Requestor Extension",
        attributes: {},
    },
    {
        mappingId: "requestTitle",
        fieldKey: "requestTitle",
        serviceId: "static",
        fieldTypeId: FormTypes.text,
        fieldId: 1004,
        fieldLabel: "Request Title",
        serviceFieldOption: [],
        isRequired: true,
        defaultValue: "",
        placeholder: "Request Title",
        attributes: {},
    },
    {
        mappingId: "requestDescription",
        fieldKey: "requestDescription",
        serviceId: "static",
        fieldTypeId: FormTypes.text,
        fieldId: 1005,
        fieldLabel: "Request Description",
        serviceFieldOption: [],
        isRequired: true,
        defaultValue: "",
        placeholder: "Request Description",
        attributes: {},
    },
    {
        mappingId: "specialCondition",
        fieldKey: "specialCondition",
        serviceId: "static",
        fieldTypeId: FormTypes.text,
        fieldId: 1006,
        fieldLabel: "Special Condition",
        serviceFieldOption: [],
        isRequired: false,
        defaultValue: "",
        placeholder: "Special Condition",
        attributes: {},
    },
    {
        mappingId: "priorityLevel",
        fieldKey: "priorityLevel",
        serviceId: "static",
        fieldTypeId: FormTypes.dropdownlist,
        fieldId: 1007,
        fieldLabel: "Priority Level",
        serviceFieldOption: [
            { value: "", label: "Select Priority", fieldId: 1007 },
            { value: "low", label: "Low", fieldId: 1007 },
            { value: "medium", label: "Medium", fieldId: 1007 },
            { value: "high", label: "High", fieldId: 1007 }
        ],
        isRequired: true,
        defaultValue: "",
        placeholder: "Priority Level",
        attributes: {},
    },
    {
        mappingId: "requestorUnit",
        fieldKey: "requestorUnit",
        serviceId: "static",
        fieldTypeId: FormTypes.text,
        fieldId: 1008,
        fieldLabel: "Requestor Unit",
        serviceFieldOption: [],
        isRequired: false,
        defaultValue: "",
        placeholder: "Requestor Unit",
        attributes: {},
    },
];
