export const RequestType = {
  SelfRequest: 1,
  RequestOnBehalf: 2,
};

export const FontAwsomeIcons = [
  {
    value: "fa-bullseye-pointer",
    label: "fa-bullseye-pointer",
    icon: "fa-bullseye-pointer",
    color: "#6c7380",
  },
  {
    value: "fa-users",
    label: "fa-users",
    icon: "fa-users",
    color: "#6c7380",
  },
  {
    value: "fa-coins",
    label: "fa-coins",
    icon: "fa-coins",
    color: "#6c7380",
  },
  {
    value: "fa-screen-users",
    label: "fa-screen-users",
    icon: "fa-screen-users",
    color: "#6c7380",
  },
  {
    value: "fa-cogs",
    label: "fa-cogs",
    icon: "fa-cogs",
    color: "#6c7380",
  },
  {
    value: "fa-globe",
    label: "fa-globe",
    icon: "fa-globe",
    color: "#6c7380",
  },
  {
    value: "fa-gauge",
    label: "fa-gauge",
    icon: "fa-gauge",
    color: "#6c7380",
  },
  {
    value: "fa-scale-balanced",
    label: "fa-scale-balanced",
    icon: "fa-scale-balanced",
    color: "#6c7380",
  },
  {
    value: "fa-file",
    label: "fa-file",
    icon: "fa-file",
    color: "#6c7380",
  },
  {
    value: "fa-download",
    label: "fa-download",
    icon: "fa-download",
    color: "#6c7380",
  },
  {
    value: "fa-circle-info",
    label: "fa-circle-info",
    icon: "fa-circle-info",
    color: "#6c7380",
  },
  {
    value: "fa-gear",
    label: "fa-gear",
    icon: "fa-gear",
    color: "#6c7380",
  },
  {
    value: "fa-grid-2",
    label: "fa-grid-2",
    icon: "fa-grid-2",
    color: "#6c7380",
  },
  {
    value: "fa-bookmark",
    label: "fa-bookmark",
    icon: "fa-bookmark",
    color: "#6c7380",
  },
  {
    value: "fa-address-book",
    label: "fa-address-book",
    icon: "fa-address-book",
    color: "#6c7380",
  },
  {
    value: "fa-earth-americas",
    label: "fa-earth-americas",
    icon: "fa-earth-americas",
    color: "#6c7380",
  },

  {
    value: "fa-landmark",
    label: "fa-landmark",
    icon: "fa-landmark",
    color: "#6c7380",
  },
  {
    value: "fa-shield",
    label: "fa-shield",
    icon: "fa-shield",
    color: "#6c7380",
  },
  {
    value: "fa-books",
    label: "1fa-books2",
    icon: "fa-books",
    color: "#6c7380",
  },
  {
    value: "fa-toolbox",
    label: "fa-toolbox",
    icon: "fa-toolbox",
    color: "#6c7380",
  },
  {
    value: "fa-money-bills-simple",
    label: "fa-money-bills-simple",
    icon: "fa-money-bills-simple",
    color: "#6c7380",
  },
  {
    value: "fa-gear-complex",
    label: "fa-gear-complex",
    icon: "fa-gear-complex",
    color: "#6c7380",
  },
  {
    value: "fa-chart-simple-horizontal",
    label: "fa-chart-simple-horizontal",
    icon: "fa-chart-simple-horizontal",
    color: "#6c7380",
  },
  {
    value: "fa-bell-ring",
    label: "fa-bell-ring",
    icon: "fa-bell-ring",
    color: "#6c7380",
  },
  {
    value: "fa-arrows-retweet",
    label: "fa-arrows-retweet",
    icon: "fa-arrows-retweet",
    color: "#6c7380",
  },
  {
    value: "fa-arrow-down-to-square",
    label: "fa-arrow-down-to-square",
    icon: "fa-arrow-down-to-square",
    color: "#6c7380",
  },
  {
    value: "fa-cloud",
    label: "fa-cloud",
    icon: "fa-cloud",
    color: "#6c7380",
  },
  {
    value: "fa-paperclip",
    label: "fa-paperclip",
    icon: "fa-paperclip",
    color: "#6c7380",
  },
  {
    value: "fa-folder",
    label: "fa-folder",
    icon: "fa-folder",
    color: "#6c7380",
  },
  {
    value: "fa-user-pilot",
    label: "fa-user-pilot",
    icon: "fa-user-pilot",
    color: "#6c7380",
  },
  {
    value: "fa-objects-column",
    label: "fa-objects-column",
    icon: "fa-objects-column",
    color: "#6c7380",
  },
  {
    value: "fa-grid-round-2-plus",
    label: "fa-grid-round-2-plus",
    icon: "fa-grid-round-2-plus",
    color: "#6c7380",
  },
  {
    value: "fa-flag-swallowtail",
    label: "fa-flag-swallowtail",
    icon: "fa-flag-swallowtail",
    color: "#6c7380",
  },
  {
    value: "fa-envelope-open-text",
    label: "fa-envelope-open-text",
    icon: "fa-envelope-open-text",
    color: "#6c7380",
  },

  {
    value: "fa-house",
    label: "fa-house",
    icon: "fa-house",
    color: "#6c7380",
  },

  {
    value: "fa-circle-user",
    label: "fa-circle-user",
    icon: "fa-circle-user",
    color: "#6c7380",
  },

  { value: "fa-list", label: "fa-list", icon: "fa-list", color: "#6c7380" },
  { value: "fa-inbox", label: "fa-inbox", icon: "fa-inbox", color: "#6c7380" },
  { value: "fa-book", label: "fa-book", icon: "fa-book", color: "#6c7380" },

  {
    value: "fa-pen-to-square",
    label: "fa-pen-to-square",
    icon: "fa-pen-to-square",
    color: "#6c7380",
  },
  {
    value: "fa-browser",
    label: "fa-browser",
    icon: "fa-browser",
    color: "#6c7380",
  },

  { value: "fa-gavel", label: "fa-gavel", icon: "fa-gavel", color: "#6c7380" },
  {
    value: "fa-hammer-brush",
    label: "fa-hammer-brush",
    icon: "fa-hammer-brush",
    color: "#6c7380",
  },
  {
    value: "fa-wrench-simple",
    label: "fa-wrench-simple",
    icon: "fa-wrench-simple",
    color: "#6c7380",
  },
  {
    value: "fa-chart-tree-map",
    label: "fa-chart-tree-map",
    icon: "fa-chart-tree-map",
    color: "#6c7380",
  },
  {
    value: "fa-diagram-subtask",
    label: "fa-diagram-subtask",
    icon: "fa-diagram-subtask",
    color: "#6c7380",
  },
  {
    value: "fa-diagram-project",
    label: "fa-diagram-project",
    icon: "fa-diagram-project",
    color: "#6c7380",
  },
  {
    value: "fa-chart-user",
    label: "fa-chart-user",
    icon: "fa-chart-user",
    color: "#6c7380",
  },

  {
    value: "fa-thumbtack",
    label: "fa-thumbtack",
    icon: "fa-thumbtack",
    color: "#6c7380",
  },
  {
    value: "fa-comments",
    label: "fa-comments",
    icon: "fa-comments",
    color: "#6c7380",
  },
  { value: "fa-gears", label: "fa-gears", icon: "fa-gears", color: "#6c7380" },
  {
    value: "fa-paper-plane",
    label: "fa-paper-plane",
    icon: "fa-paper-plane",
    color: "#6c7380",
  },
  { value: "fa-city", label: "fa-city", icon: "fa-city", color: "#6c7380" },
  {
    value: "fa-sliders",
    label: "fa-sliders",
    icon: "fa-sliders",
    color: "#6c7380",
  },
  {
    value: "fa-ticket",
    label: "fa-ticket",
    icon: "fa-ticket",
    color: "#6c7380",
  },

  {
    value: "fa-briefcase",
    label: "fa-briefcase",
    icon: "fa-briefcase",
    color: "#6c7380",
  },
  {
    value: "fa-compass",
    label: "fa-compass",
    icon: "fa-compass",
    color: "#6c7380",
  },
  {
    value: "fa-binoculars",
    label: "fa-binoculars",
    icon: "fa-binoculars",
    color: "#6c7380",
  },
  {
    value: "fa-right-to-bracket",
    label: "fa-right-to-bracket",
    icon: "fa-right-to-bracket",
    color: "#6c7380",
  },
  {
    value: "fa-handshake",
    label: "fa-handshake",
    icon: "fa-handshake",
    color: "#6c7380",
  },
  {
    value: "fa-layer-group",
    label: "fa-layer-group",
    icon: "fa-layer-group",
    color: "#6c7380",
  },

  {
    value: "fa-business-time",
    label: "fa-business-time",
    icon: "fa-business-time",
    color: "#6c7380",
  },
  { value: "fa-link", label: "fa-link", icon: "fa-link", color: "#6c7380" },
  {
    value: "fa-badge-check",
    label: "fa-badge-check",
    icon: "fa-badge-check",
    color: "#6c7380",
  },
  {
    value: "fa-pen-fancy",
    label: "fa-pen-fancy",
    icon: "fa-pen-fancy",
    color: "#6c7380",
  },

  {
    value: "fa-chart-simple",
    label: "fa-chart-simple",
    icon: "fa-chart-simple",
    color: "#6c7380",
  },

  {
    value: "fa-signal-bars",
    label: "fa-signal-bars",
    icon: "fa-signal-bars",
    color: "#6c7380",
  },
  {
    value: "fa-code-compare",
    label: "fa-code-compare",
    icon: "fa-code-compare",
    color: "#6c7380",
  },
  {
    value: "fa-atom-simple",
    label: "fa-atom-simple",
    icon: "fa-atom-simple",
    color: "#6c7380",
  },
  {
    value: "fa-car-side",
    label: "fa-car-side",
    icon: "fa-car-side",
    color: "#6c7380",
  },
  {
    value: "fa-envelopes",
    label: "fa-envelopes",
    icon: "fa-envelopes",
    color: "#6c7380",
  },
  { value: "fa-clock", label: "fa-clock", icon: "fa-clock", color: "#6c7380" },
  {
    value: "fa-passport",
    label: "fa-passport",
    icon: "fa-passport",
    color: "#6c7380",
  },
  {
    value: "fa-car-building",
    label: "fa-car-building",
    icon: "fa-car-building",
    color: "#6c7380",
  },
  {
    value: "fa-computer-speaker",
    label: "fa-computer-speaker",
    icon: "fa-computer-speaker",
    color: "#6c7380",
  },
  {
    value: "fa-credit-card",
    label: "fa-credit-card",
    icon: "fa-credit-card",
    color: "#6c7380",
  },
  {
    value: "fa-newspaper",
    label: "fa-newspaper",
    icon: "fa-newspaper",
    color: "#6c7380",
  },
  { value: "fa-table", label: "fa-table", icon: "fa-table", color: "#6c7380" },
  { value: "fa-flag", label: "fa-flag", icon: "fa-flag", color: "#6c7380" },

  {
    value: "fa-network-wired",
    label: "fa-network-wired",
    icon: "fa-network-wired",
    color: "#6c7380",
  },
];
